version: "3.0"
services:
  mongoDB:
    image: mongo
    ports:
      - "27017:27017"
  kairos-front:
    build: kairos-front
    ports:
      - "8080:8080"
  kairos-server:
    build: kairos-server
    ports: 
      - "3003:3003"
    links:
      - mongoDB
    depends_on:
      - mongoDB
  
